import torch
#재밌는거 하는거 봐라
DEVICE = torch.device('cuda:0')
CHECKPOINT_DIR = "./checkpoint"
VERSION = "v1"

N_EPOCH = 300

BATCH_SIZE = 512
NUM_WORKERS = 2

LEARNING_RATE = 1e-5
WEIGHT_DECAY = 5e-4
ADAM_EPS = 5e-9
SCHEDULER_FACTOR = 0.9
SCHEDULER_PATIENCE = 10

WARM_UP_STEP = 100

DROPOUT_RATE = 0.1